
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 06 13:50:44 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 6;
  public static final int OP_AND = 18;
  public static final int MAYOR_IGUAL_Q = 14;
  public static final int DECIMAL = 4;
  public static final int MENOR_IGUAL_Q = 15;
  public static final int OP_NOT = 20;
  public static final int OP_OR = 17;
  public static final int POT = 9;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int DIFERENTE = 16;
  public static final int DIV = 8;
  public static final int PAR_IZQ = 10;
  public static final int MENOR_Q = 13;
  public static final int error = 1;
  public static final int PAR_DER = 11;
  public static final int ENTERO = 3;
  public static final int OP_XOR = 19;
  public static final int MAS = 5;
  public static final int MAYOR_Q = 12;
}

